# Generated by Django 4.2.11 on 2024-04-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0192_merge_20240405_1154'),
        ('discount', '0080_add_unique_type_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionrule',
            name='gifts',
            field=models.ManyToManyField(blank=True, related_name='+', to='product.productvariant'),
        ),
    ]
