# Generated by Django 3.2.17 on 2023-02-09 11:28

from django.db import migrations, models

import weenspace.core.utils.json_serializer
import weenspace.webhook.validators


class Migration(migrations.Migration):
    dependencies = [
        ("webhook", "0008_webhook_subscription_query"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhook",
            name="custom_headers",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=weenspace.core.utils.json_serializer.CustomJsonEncoder,
                null=True,
                validators=[weenspace.webhook.validators.custom_headers_validator],
            ),
        ),
    ]
